language: python

stages:
  - test
  - build
  - coverage
  - deploy

install:
  - pip install -r requirements.txt
  - pip install .

script: python -m pytest

jobs:
  include:
    - stage: test
      python: "3.7"
      before_install: pip install tox
      script: make test
      dist: xenial

    - python: pypy3
      before_install: pip install tox
      script: make test
      dist: xenial

    - stage: deploy
      script: python setup.py sdist
      deploy:
        provider: pypi
        user: "__token__"
        on:
          tags: true
          repo: boxed/hammett
